// src/components/Navbar.tsx
"use client";

import { faGithub, faLinkedin } from "@fortawesome/free-brands-svg-icons";
import { faEnvelope } from "@fortawesome/free-regular-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import Link from "next/link";
import { usePathname } from "next/navigation";

const LINKS = {
  "/": "Home",
  "/about": "About",
  "/blog": "Blog",
  "/portfolio": "Portfolio",
};

const EXTERNAL = {
  "mailto:dominiccarrington@mail.com": <FontAwesomeIcon icon={faEnvelope} />,
  "//github.com/dominiccarrington": <FontAwesomeIcon icon={faGithub} />,
  "//linkedin.com/in/dominic-carrington-0b00a2207/": (
    <FontAwesomeIcon icon={faLinkedin} />
  ),
};

export default function Navbar() {
  const pathname = usePathname();

  return (
    <nav className="flex flex-col gap-y-2 px-8 py-2 md:py-4 md:flex-row border-b border-b-slate-700 mb-4">
      <ul className="flex justify-center gap-x-4 text-xl md:order-2 md:ml-auto md:justify-end">
        {Object.keys(EXTERNAL).map((href) => (
          <li key={href}>
            <a href={href} target="_blank">
              {EXTERNAL[href as keyof typeof EXTERNAL]}
            </a>
          </li>
        ))}
      </ul>

      <ul className="flex gap-x-4 md:justify-start">
        {Object.keys(LINKS).map((href) => (
          <li className="flex w-full items-center justify-center" key={href}>
            <Link
              href={href}
              className={`${pathname === href ? "font-semibold underline" : ""}`}
            >
              {LINKS[href as keyof typeof LINKS]}
            </Link>
          </li>
        ))}
      </ul>
    </nav>
  );
}

// components/Navbar.vue
<template>
  <b-navbar toggleable="md" type="light" variant="light">
    <b-navbar-brand href="/" class="d-md-none">
      Dominic Carrington
    </b-navbar-brand>
    <b-navbar-toggle target="navbar" />

    <b-collapse id="navbar" is-nav>
      <b-navbar-nav>
        <navlink href="/">
          Home
        </navlink>
        <navlink href="/blog">
          Blog
        </navlink>
        <navlink href="/mods">
          Mods
        </navlink>
        <navlink href="/projects">
          Projects
        </navlink>
        <navlink href="/tools">
          Tools
        </navlink>
      </b-navbar-nav>

      <b-navbar-nav class="ml-auto">
        <b-nav-item href="https://github.com/dominiccarrington">
          <fa :icon="faGithub" />
        </b-nav-item>

        <b-nav-item href="mailto:dominiccarrington@mail.com">
          @
        </b-nav-item>
      </b-navbar-nav>
    </b-collapse>
  </b-navbar>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';
import { faGithub } from '@fortawesome/free-brands-svg-icons';
import Navlink from '~/components/Navlink.vue';

@Component({
  components: {
    Navlink
  }
})
export default class Navbar extends Vue {
  get faGithub() {
    return faGithub;
  }
}
</script>
