// pages/blog/index.vue
<template>
  <div>
    <h1>My Blog</h1>
    <TableOfPosts :posts="posts"/>
  </div>
</template>

<script>
import BlogTags from "~/components/Blog/Tags.vue";
import TableOfPosts from "~/components/Blog/TableOfPosts.vue";

export default {
  layout: 'blogpost',
  async asyncData({app}) {
    // Move sorting into component
    const blogposts = await app.$axios.$get("/blogposts.json");

    let posts = [];
    for (let id in blogposts) {
      blogposts[id]["id"] = id;
      posts.push(blogposts[id]);
    }

    return {
      posts
    };
  },
  head() {
    return {
      title: "Dominic Carrington's Blog"
    };
  },
  components: {
    BlogTags,
    TableOfPosts
  }
}
</script>

// src/app/blog/page.tsx
import { getSortedPostsData, getTags } from "@/lib/posts";
import { Metadata } from "next";

import BlogPosts from "./BlogPosts";

export const metadata: Metadata = {
  title: "Blog | Dominic Carrington"
};

export default function Blog() {
  const tags = getTags();
  const posts = getSortedPostsData();

  return (
    <main className="px-8">
      <h1>Blog</h1>
      <p></p>

      <BlogPosts tags={tags} posts={posts} />
    </main>
  );
}
